config/routes.rb
Rails.application.routes.draw do

  DynamicRouter.load
  
  scope "(:locale)", :locale => /en|es/ do  
    DynamicBlogRouter.load
    resources :blogs, :except => ['show', 'update', 'destroy']
    get    'blogs/:id' => 'blogs#show', :as => 'show_blog'
    put    'blogs/:id' => 'blogss#update'
    delete 'blogs/:id' => 'blogs#destroy'
    
    resources :subpages

    resources 'contacts', only: [:new, :create]
    get 'contact' => 'contacts#new'

    devise_for :admins
    resources :photos

    devise_for :users
    root 'pages#home'

    get 'blog' => 'pages#blog'
    get 'about' => 'pages#about'
  
    get 'album' => 'pages#album'
    get 'weddings' => 'pages#weddings'
    get 'lifestyle' => 'pages#lifestyle'

    get 'admin/photos' => 'pages#admin_photos'
    get 'admin/pages' => 'pages#admin_pages'
    get 'admin/blog' => 'pages#admin_blog'
  end
  

end

app/views/pages/_datatable.html.erb
<div class='row'>
	<div class='col-md-10 col-md-offset-1'>
		<table class='table'>
			<thead>
				<tr>
					<th>ID</th>
					<th>NAME</th>
					<th>PHOTO</th>
					<th>CATEGORY</th>
					<th>SHOW</th>
					<th>EDIT</th>
					<th>DELETE</th>

				</tr>
			</thead>	
			<tbody>
				<% @items.each do |item| %>
					
					<!-- Set show + edit paths --> 
					<% case request.original_url.split('admin/')[1][0,4] %>
					<% when 'page' %>
						<% show_path = subpage_path(item) %>
						<% edit_path = edit_subpage_path(item) %>
					<% when 'phot' %>
						<% show_path = photo_path(item) %>
						<% edit_path = edit_photo_path(item) %>
					<% when 'blog' %>
						<% show_path = show_blog_path(item) %>
						<% edit_path = edit_blog_path(item) %>
					<% else %>
						<% show_path = root_path %>
						<% edit_path = root_path %>
					<% end %>

					<tr>
						<td><%= item.id %></td>
						<td><%= item.name %></td>
						<td><%= link_to photo_path(item) do %>
							<%= image_tag item.image.url(:thumb), class: 'thumb' %>
						<% end %></td>
						<td><%= item.category %></td>
						<td><%= button_to 'Show', show_path, method: :get, class: 'btn btn-small' %></td>
        			<td><%= button_to 'Edit', edit_path, method: :get, class: 'btn btn-small' %></td>
        			<td><%= button_to 'Delete', item, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-small' %></td>
					</tr>
				<% end %>
			</tbody>
		</table>

	</div>
</div>

<center><%= will_paginate @items, renderer: BootstrapPagination::Rails %></center>

app/views/pages/_masonryblogposts.html.erb
<div class="transitions-enabled col1" id="blogs">
  <% @blogs.reverse.each do |b| %>
    <div class="box panel panel-default" id="masonry-container">
      <%= link_to (image_tag b.image.url(:display)), send("#{b.category}_#{b.id}_path") %>
      <div class='container' id='blogs'>
      	<h3 class='blog_title'> <%= b.name %> </h3>
	      <p class='blog_date'>
	      <%= I18n.l b.created_at %> 
	      </p>
	  </div>
    </div>
  <% end %>
</div>

app/views/pages/_masonryphotos.html.erb
<div class="transitions-enabled gallery-up" id="posts">
  <% @subpages.reverse.each do |p| %>
    <div class="box panel panel-default">
      <%= link_to (image_tag p.image.url(:display)), send("#{p.category}_#{p.id}_path") %>
    </div>
  <% end %>
</div>

app/views/pages/_photos.html.erb
<div class='hermitage_gallery'>

<% if @photos %>
	<%= render_gallery_for @photos, list_tag: :ul, item_tag: :li, list_class: 'thumbnails', item_class: 'span8'  %> 
<% end %>

</div>

app/views/pages/about.html.erb
<div class='shift_about_up'>

	<%= render 'photos' %>

	<div class='col-md-8 col-md-offset-2 texts'>
	<p>
	Sttilo somos Juanlu y Joy, dos jóvenes con una visión actual y creativa del mundo audiovisual. Ambos fuimos atrapados por la fotografía y el vídeo y hemos intentado transmitir desde entonces nuestra pasión a las parejas que confían en nuestro trabajo. Nos gusta investigar, viajar, crear y pensar alrededor de nuestros proyectos, la inspiración es un recurso muy valioso que no se puede encontrar en un único lugar, de ahí que necesitemos movernos para estar siempre innovado y descubriendo formas de expresar lo que vemos a través de nuestros ojos.
	</p>
	<p>
	No vemos la fotografía o el vídeo como un instrumento de trabajo, Sttilo es algo que va más allá del simple reportaje de boda, queremos ser parte de tu felicidad y para ello tratamos de contagiarnos con esa misma energía, creando una relación con nuestros clientes que sea fluida, divertida y sincera. Queremos que tu día sea algo especial y la única manera de que eso ocurra es que nosotros estemos completamente inmersos en la felicidad de vuestra celebración.
	</p>
	</div>

</div>

app/views/pages/admin_blog.html.erb
<div class='shift_tables_up'>
<h3 class='text-center'><%= link_to 'Add Blog Post', new_blog_path, class: 'btn btn-primary btn-sm' %></h3>

<div class='col-md-10 col-md-offset-1 text-right'>
<%= form_tag(admin_blog_path, :method => "get", id: "search-form") do %>
	<%= text_field_tag :search, params[:search], placeholder: "Search for...", id: 'search', class: "form-control" %>
	<%= submit_tag "Search", :name => nil, class: "btn btn-small" %>
<% end %>
</div>

<%= render 'datatable' %>

</div>

app/views/pages/admin_pages.html.erb
<h3 class='text-center'><%= link_to 'Add Subpage', new_subpage_path, class: 'btn btn-primary btn-sm' %></h3>

<div class='col-md-10 col-md-offset-1 text-right'>
<%= form_tag(admin_pages_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search for...", class: "form-control" %>
<%= submit_tag "Search", :name => nil, class: "btn btn-small" %>
<% end %>
</div>

<%= render 'datatable' %>

app/views/pages/admin_photos.html.erb
<h3 class='text-center'><%= link_to 'Add Photo', new_photo_path, class: 'btn btn-primary btn-sm' %></h3>
<div class='col-md-10 col-md-offset-1 text-right'>
<%= form_tag(admin_photos_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search for...", class: "form-control" %>
<%= submit_tag "Search", :name => nil, class: "btn btn-small" %>
<% end %>
</div>
<%= render 'datatable' %>

app/views/pages/album.html.erb
<% if !@photos %>
  <h1 class='text-center texts shift-up' id='coming_soon'><%= t('coming_soon')%></h1>
<% end %>
<%= render 'masonryphotos' %>

app/views/pages/blog.html.erb
<div class='shift_forms_up'>

<%= render 'masonryblogposts' %>

</div>

app/views/pages/home.html.erb
<%= render 'masonryphotos' %>

app/views/pages/lifestyle.html.erb
<% if !@photos %>
  <h1 class='text-center texts shift-up' id='coming_soon'><%= t('coming_soon')%></h1>
<% end %>
<%= render 'masonryphotos' %>

app/views/pages/weddings.html.erb
<div class='shift_gallery_up'>

<%= render 'masonryphotos' %>

</div>