config/routes.rb
Rails.application.routes.draw do

  DynamicRouter.load
  
  scope "(:locale)", :locale => /en|es/ do  
    DynamicBlogRouter.load
    resources :blogs, :except => ['show', 'update', 'destroy']
    get    'blogs/:id' => 'blogs#show', :as => 'show_blog'
    put    'blogs/:id' => 'blogss#update'
    delete 'blogs/:id' => 'blogs#destroy'
    
    resources :subpages

    resources 'contacts', only: [:new, :create]
    get 'contact' => 'contacts#new'

    devise_for :admins
    resources :photos

    devise_for :users
    root 'pages#home'

    get 'blog' => 'pages#blog'
    get 'about' => 'pages#about'
  
    get 'album' => 'pages#album'
    get 'weddings' => 'pages#weddings'
    get 'lifestyle' => 'pages#lifestyle'

    get 'admin/photos' => 'pages#admin_photos'
    get 'admin/pages' => 'pages#admin_pages'
    get 'admin/blog' => 'pages#admin_blog'
  end
  

end

app/views/layouts/_footer.html.erb
<footer class="footer texts">
  <small>
  	<center>
    Todas las fotografías <i class="fa fa-copyright"></i> Sttilo 2015. Fotógrafos de boda Córdoba y Malaga. Por favor, no hacer uso de ellas sin el consentimiento escrito de Sttilo. <br>
    Created by <%= link_to 'Michael Gordon', 'https:michaelgordon.io', {:style =>'color:grey;'} %>
  </center>
  </small>
</footer>

app/views/layouts/_header.html.erb
<!-- Social Media Icons -->
<nav class="navbar navbar-default">
  <div class="container-fluid", style="margin:10px 10px 0 0;">

  <div id="language_menu">
<ul style='display:in-line;list-style-type:none;'>
<li class=<%= 'active' if I18n.locale == I18n.default_locale %>>
  <%= link_to "EspaÑol".upcase, locale_url_es('es'), :locale=>'es' %>
</li> 
&nbsp;|&nbsp;
<li class=<%= 'active' if I18n.locale != I18n.default_locale %>>
  <%= link_to "English".upcase, locale_url_en('en'), :locale=>'en' %>
</li>
</ul>
  </div>
  <span style='float: left;margin: 10px 0 0 0;'>
    <% if current_user.try(:admin?) %>
    <%= link_to 'Logout'.upcase, destroy_user_session_path, {:style => 'font-size:90%;', method: :delete, :class => 'headers'} %>
    &nbsp; // &nbsp; 
    <%= link_to "Subpages".upcase, admin_pages_path, {:style => 'font-size:90%;', :class => "headers #{'active_header' if current_page?(admin_pages_path)}", id:'photosButton'}  %>
    &nbsp; // &nbsp; 
    <%= link_to "Photos".upcase, admin_photos_path, {:style => 'font-size:90%;', :class => "headers #{'active_header' if current_page?(admin_photos_path)}"} %>
    &nbsp; // &nbsp; 
    <%= link_to "Blog".upcase, admin_blog_path, {:style => 'font-size:90%;', :class => "headers #{'active_header' if current_page?(admin_blog_path)}"} %>
  <% else %>
    <%= link_to 'Login'.upcase, new_user_session_path, {:style => 'font-size:90%;color:white;', :class => 'headers'} %>
  <% end %>
  </span>
  
  <br>
  <br>
    <span style='float: right'>
      <ul>
    <%= link_to "<i class='fa fa-twitter'></i>".html_safe, 'https://twitter.com/sttilophoto' %>
    &nbsp;
    <%= link_to "<i class='fa fa-facebook'></i>".html_safe, 'https://www.facebook.com/sttiloweddingphotography' %>
    &nbsp;
    <%= link_to "<i class='fa fa-instagram'></i>".html_safe, 'http://www.enjoygram.com/sttiloweddingphotography' %>
    &nbsp;
    <%= link_to "<i class='fa fa-pinterest'></i>".html_safe, 'https://www.pinterest.com/sttilow/' %>
  </ul>
  </span>

  </nav>    
    
</div>

<!-- Company Logo -->
<div class="logo"><%= link_to image_tag('logotipo.png', alt: 'root'), root_path %></div>

<!-- Navigation Bar -->
<nav class="navbar navbar-default">
  <div class="container-fluid">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      	<li class=<%= 'active' if current_page?(weddings_path) %>><%= link_to t('menu.weddings').upcase, weddings_path, :class => 'headers' %></li>
        <li class=<%= 'active' if current_page?(lifestyle_path) %>><%= link_to t('menu.lifestyle').upcase, lifestyle_path, :class => 'headers' %></li>
       <li class=<%= 'active' if current_page?(album_path) %>><%= link_to t('menu.album').upcase, album_path, :class => 'headers' %></li>
       <li class=<%= 'active' if current_page?(about_path) %>><%= link_to t('menu.about').upcase, about_path, :class => 'headers' %></li>
       <li class=<%= 'active' if current_page?(blog_path) %>><%= link_to t('menu.blog').upcase, blog_path, :class => 'headers' %></li>
       <li class=<%= 'active' if current_page?(contact_path) %>><%= link_to t('menu.contact').upcase, contact_path, :class => 'headers' %></li>
      </ul>
    </div>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

	<!-- google fonts -->
	<link href='http://fonts.googleapis.com/css?family=Raleway|Merriweather' rel='stylesheet' type='text/css'>

	<!-- bootstrap -->
	<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

	<!-- favicon -->
	<%= favicon_link_tag 'logotipo.ico' %>

  <title>Sttilo | WEDDING PHOTOGRAPHY</title>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


</head>
<body id='primary-content'>

    <%= render 'layouts/header' %>
	<%= yield %>
	<%= render "layouts/footer" %>

</body>
</html>